### ISSUE TITLE
Use of errors

### ISSUE THREAD

**Issue by Pinank** [jitsi/lib-jitsi-meet#1145]
How can i use following errors,
![Screenshot 2020-05-05 at 3 26 42 PM](https://user-images.githubusercontent.com/3683505/81054703-ea21e900-8ee4-11ea-9d46-8062647caed9.png)

i tried using following way but it didn't worked
```
connection.addEventListener(
JitsiMeetJS.events.connection.CONNECTION_DROPPED_ERROR,
(err: any) => {
   console.error("Connection Dropped!", err);
});
```

**Comment by ashitikov** [comment]
You can use 
`connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_FAILED, (err, msg) => {
if (err === JitsiMeetJS.events.connection.CONNECTION_DROPPED_ERROR) {
...
})`

this is pseudocode, I didn't check it for validity. But basically, you can't use addEventListener for errors, because this is for events only. So in this case you should listen CONNECTION_FAILED event and check for an error you wish inside callback.
