### ISSUE TITLE
Audio levels of remote tracks are 10 times quieter than local tracks

### ISSUE THREAD

**Issue by sapkra** [jitsi/lib-jitsi-meet#1355]
I've implemented dynamic rings for the audio levels and noticed that the remote tracks are pretty much not visible.

I already tested it on the same machine using the exact same microphone by logging the audio levels.

**Comment by jallamsetty1** [comment]
The local audio levels are gathered from the AudioContext whereas the remote audio levels are reported by the RTCRtpPeerconnection - https://www.w3.org/TR/webrtc/#dom-rtcrtpreceiver-getsynchronizationsources
There is a difference in the audio levels reported by each of these mechanisms, we did use a scale factor of 2.5 for the remote levels to bring them up the local audio levels and is working well on meet.jit.si.
The older way for gathering remote stats from peerconnection getStats is very process intensive since you have to process the whole getStats table every 200ms. You can disable it by returning false here and check if it makes a difference https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/browser/BrowserCapabilities.js#L153
I am planning to close this issue since this is not a bug.

**Comment by sapkra** [comment]
What about normalizing the audio levels inside lib-jitsi-meet, so that every client implementing this library has the same multiplier?
btw. my multiplier is 10.

**Comment by jallamsetty1** [comment]
Its already been done here - https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/statistics/RTPStatsCollector.js#L308
and this seems to be working well for jitsi-meet clients.

**Comment by sapkra** [comment]
I will close it for now and investigate further by myself. Currently I have no idea why I need an higher multiplier than jitsi-meet.
