### ISSUE TITLE
Consider reenabling RTX on Firefox

### ISSUE THREAD

**Issue by mavit** [jitsi/lib-jitsi-meet#1446]
The comment in commit 0cffc06 says that RTX was disabled in Firefox because of https://bugzilla.mozilla.org/show_bug.cgi?id=1668028.  However, that bug is marked as fixed in Firefox 84, which has now been released.  It may now be time to undo that commit.

**Comment by fippo** [comment]
@jallamsetty1 thoughts? Maybe improve the condition by adding the FF version (not sure what the current ESR version is...)

**Comment by jallamsetty1** [comment]
> @jallamsetty1 thoughts? Maybe improve the condition by adding the FF version (not sure what the current ESR version is...)

I tested the fix immediately when the bug was fixed and everything was fine. I tried to add the version check for FF84 and re-enable it in Dec and saw freezes again. I didn't get a chance then to debug if its the same issue or something new. I will try to test it again this week and see what happens.
