### ISSUE TITLE
Conference onRemoteTrackAdded videoType is the previous remoteTrack's videoType

### ISSUE THREAD

**Issue by 08BRYLL23** [jitsi/lib-jitsi-meet#1649]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---  When I add a local track of type video/desktop, it seems that when I check on onRemoteTrackAdded (function for **JitsiMeetJS.events.conference.TRACK_ADDED**), it seems the videoType is undefined. If I try to create another local track, it seems to get the previous one's videoType. (One thing to take note of is that the previous value only happens when I try to retrieve the videoType but when I check in the logs the videoType seems to be accurate)

## Current behavior
---onRemoteTrackAdded the videoType of the remote track is the previous's videoType

## Expected Behavior
---onRemoteTrackAdded the videoType of the remote track should be the videoType that was added

## Possible Solution
---

## Steps to reproduce
---
![Screen Shot 2021-07-01 at 11 50 54 AM](https://user-images.githubusercontent.com/40222666/124087526-227a7400-da63-11eb-9266-38be16c879e8.png)

# Environment details
---

**Comment by jadhavsaurabh** [comment]
@08BRYLL23 @damencho Any updates on this?

**Comment by damencho** [comment]
Do you reproduce with latest master? If yes, give us a simple example to reproduce it, thanks.

**Comment by jadhavsaurabh** [comment]
@damencho 

https://meet.jit.si/libs/lib-jitsi-meet.min.js?v=5666.2368 I am using this minified lib-jitsi-meet
````
let room = await connection.initJitsiConference('name', {
  enableLayerSuspension: false,
  p2p: {
              enabled: false,
              enableUnifiedOnChrome: true,
              preferredCodec: 'VP9',
              disableH264: true,
  },
  e2eping: { pingInterval: -1 }
});
````

and I am listening to events like this
```
room &&
      room.on(JitsiMeetJS.events.conference.TRACK_ADDED, (track) => {
        console.log("isTrackDesktopTrack?", track, track.videoType);
        !track.isLocal() && !remoteTrackMatchesLocal(track) && onRemoteTrackAdd(track);
      });
```
Expected behaviour would be:
`isTrackDesktopTrack? {TrackObject}, "desktop"`

But I am getting
`isTrackDesktopTrack? {TrackObject}, undefined`

But after expanding the object in browsers console I can see trackObject has videoType property as `desktop`

**Comment by Jacky-Rolo** [comment]
> Do you reproduce with latest master? If yes, give us a simple example to reproduce it, thanks.

Hi @damencho 

I fork `jitis-meet (jitsi-meet_6835 )` and add some console.log when `TRACK_ADDED` event

https://github.com/Jacky-Rolo/jitsi-meet/blob/issue/%231649/conference.js#L2111-L2117  
![image](https://user-images.githubusercontent.com/75233579/149913418-27607c1b-0da5-479e-a4ae-973cf8839518.png)


## re-produce steps
1. clone https://github.com/Jacky-Rolo/jitsi-meet/tree/issue/%231649
2. `npm i && npm start`
3. open 2 browser tab
4. `#1` tab, create a room and open dev tool
5. `#2` tab, join the room **WITHOUT** camera
6. `#2` tab sharing screen
7. `#1` tab, search `=====>`

You can see, `track.videoType` is **undefined** when receiving track. Need to wait a while.  

![Screen Shot 2022-01-18 at 17 40 17](https://user-images.githubusercontent.com/75233579/149912623-785099d8-bd3e-4e49-b338-513af4cd1e9c.jpg)

**Comment by jadhavsaurabh** [comment]
@Jacky-Rolo Hey, I think the `track` is passed by reference.
So, and they are changed somewhere in async way. Hence after `500ms` of timeout we have access to correct data.

Now doubt is, Is this a **correct/expected** behaviour or minor glitch in `lib-jitsi-meet` event handlers?

**Comment by jallamsetty1** [comment]
Please note that `replaceTrack` needs to be called when you are replacing a camera track with a desktop track instead of calling `removeTrack` and `addTrack`. At the peerconnection level, the track is always being replaced so that there are no SSRC changes and no signaling is required. It is considered as a single source and therefore a TRACK_ADDED event won't be fired on the peer.

**Comment by jallamsetty1** [comment]
Also, since only one video stream is sent on a media connection in the current implementation, once the track gets added, it should only be replaced. Once the multi-stream support lands wherein you will be able to send two or more video tracks, you can then use removeTrack and addTrack. Once a local source is added, any changes to the underlying track should be made by calling replaceTrack. addTrack/removeTrack can be used to add or remove these local sources to/from the connection.

**Comment by Jacky-Rolo** [comment]
> Please note that `replaceTrack` needs to be called when you are replacing a camera track with a desktop track instead of calling `removeTrack` and `addTrack`. At the peerconnection level, the track is always being replaced so that there are no SSRC changes and no signaling is required. It is considered as a single source and therefore a TRACK_ADDED event won't be fired on the peer.

First, many thanks @jallamsetty1 's hard work.

Second, I want to ask, since `replaceTrack` would **NOT** fire `TRACK_ADDED` event, How can we know User switch to `Desktop` from `Camera` or in reverse ? What's a appropriate way to handle it ? Via `JitsiTrack`'s `TRACK_VIDEOTYPE_CHANGED` event ?

Many thanks !!

**Comment by dkgrieshammer** [comment]
@Jacky-Rolo yes you would use TRACK_VIDEOTYPE_CHANGED; I make a [PR for the docs](https://github.com/jitsi/handbook/pull/276) already. Apparently even though the event is fired pretty fast it takes some time for the actual switch in the media stream to happen - at least for us there is a significant timeout on the video stream until other participants actually see the desktop. Interestingly, this is only noticeable when switching from cam to desktop - switching back happens nearly realtime.

**Comment by Jacky-Rolo** [comment]
> ..., but the video freezes for some seconds until the desktop is visible. Seems to be less of a problem in the latest update, but still there.

Thanks your sharing @dkgrieshammer , I noticed this when I debug this issue, I feel UX are real bad.

I will test latest version recently, thanks every one.

**Comment by Jacky-Rolo** [comment]
I tested `v1389` and `7032`, unfortunately, this issue did NOT fix yet.  

I fork `Jitsi-meet` (lib-jitsi-meet `v1389`) still able re-produce it
- https://github.com/Jacky-Rolo/jitsi-meet/tree/issue/incorrect_videoType_when_sharing_screen

I add some console.log when `TRACK_ADDED`
https://github.com/Jacky-Rolo/jitsi-meet/blob/f24ede822c58b644e0efc6cda0543aa4944eb9e4/conference.js#L2123-L2132

<img width="986" alt="Screen Shot 2022-03-12 at 13 11 13" src="https://user-images.githubusercontent.com/75233579/158004775-69fe1ded-5ec6-4615-9b60-a557f6b70ece.png">

## re-produce steps
1. clone `https://github.com/Jacky-Rolo/jitsi-meet/tree/issue/incorrect_videoType_when_sharing_screen`
2. `npm i` && `npm start`
3. open 2 browser tab
4. `#1` tab, create a room and open dev tool
5. `#2` tab, join the room **WITHOUT** camera
6. `#2` tab sharing screen
7. `#1` tab, search ==>

`#1` use SHOULD receive correct `videoType` 

<img width="657" alt="Screen Shot 2022-03-12 at 13 02 56" src="https://user-images.githubusercontent.com/75233579/158004844-9bc8291b-5a50-466d-acb4-a0d0ebbcfd46.png">

cc @damencho , @jallamsetty1 can you help **re-open** this issue, thanks

**Comment by damencho** [comment]
@jallamsetty1 We don't get the track type with the signalling from jicofo right?

**Comment by damencho** [comment]
@jallamsetty1 will that be different with the multi stream support?
