### ISSUE TITLE
Allow to configure DESKTOP_SHARE_RATE and HD_BITRATE parameters

### ISSUE THREAD

**Issue by mnasyrov** [jitsi/lib-jitsi-meet#1674]
## Description

There are `HD_BITRATE` and `DESKTOP_SHARE_RATE` constants which are used by `TraceablePeerConnection.setMaxBitRate()` function. Please allow to configure them.

---

## Current behavior
`TraceablePeerConnection.setMaxBitRate()` function uses following values for the constants:
```
const DESKTOP_SHARE_RATE = 500000;
const HD_BITRATE = 2500000;
```

---

## Expected Behavior

These parameters can be configured via connection options.

---

## Environment details

lib-jitsi-meet, tag jitsi-meet_6096

**Comment by saghul** [comment]
What is your use case?

**Comment by mnasyrov** [comment]
Enabling extra quality for sharing a screen with a big resolution. It would be great if the bitrate can be  changed dynamically during the call.

**Comment by jallamsetty1** [comment]
> Enabling extra quality for sharing a screen with a big resolution. It would be great if the bitrate can be changed dynamically during the call.

Please note that these values are used only for low fps screenshare, i.e., when simulcast is disabled. Sending high bitrate unicast stream is not ideal since the bridge will suspend the screenshare for endpoints that do not have enough downlink to receive the screenshare.

Also, high resolution screenshare doesn't necessarily produce a high bps stream unless the scene is changing a lot. In that case, you might want to turn on high fps screenshare from UI->settings->more tab which enables simulcast. The bitrates used in that case are configurable through videoQuality.maxBitratesVideo.

**Comment by mnasyrov** [comment]
I'm looking an option to get better quality of streaming a high-resolution source (e.g. 4k display) via Intranet.

**Comment by icewarp** [comment]
That would be awesome.. our clients complained, that they can't screenshare locally playing videos (previews of some internal media).. we increased max FPS to 15 in jitsi, but it can't be reached in this bandwidth envelope for screen sharing.. when increased to at least HD_BITRATE, then Chrome started to send more FPS due to increased bandwidth limit..

we are doing this modification by modifying lib-jitsi-meet, but having that configurable will be much better..

**Comment by Hin-D** [comment]
> That would be awesome.. our clients complained, that they can't screenshare locally playing videos (previews of some internal media).. we increased max FPS to 15 in jitsi, but it can't be reached in this bandwidth envelope for screen sharing.. when increased to at least HD_BITRATE, then Chrome started to send more FPS due to increased bandwidth limit..
> 
> we are doing this modification by modifying lib-jitsi-meet, but having that configurable will be much better..

I have the same question. please could you share the code you modified?

**Comment by psi-4ward** [comment]
We do similar things:
```
const DESKTOP_SHARE_RATE = window.config?.desktopShareBitrate || 500000;
```

And disable the lower-resolution screenshare tracks
```js
if (this._isSharingScreen()) {
    parameters.encodings[encoding].active = hdStreamIndex.toString() === encoding;
} else {
    parameters.encodings[encoding].active = this.encodingsEnabledState[encoding];
}
```

**Comment by jallamsetty1** [comment]
We do disable the lower-resolution screenshare streams by default (unified-plan implementation). I am working on a PR that makes desktop share rate configurable.
