### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by golangaccount** [jitsi/lib-jitsi-meet#17]

**Comment by golangaccount** [comment]
ERSION=`./get-version.sh` && sed -i'' -e s/{#COMMIT_HASH#}/${VERSION}/g lib-jitsi-meet.js

**Comment by asvetlenko** [comment]
I have problems with install too, and I found what is going wrong. lib-jitsi-meet use dependency: "socket.io-client": "1.3.6" . And it crashed process of the installation. 
If you try to install only socket.io-client with version 1.3.6 you will get errors (npm install socket.io-client@1.3.6), because it version very bad.
If developer's "lib-jitsi-meet" change version of the dependency to "socket.io-client": "1.*" you will not get errors.

**Comment by asvetlenko** [comment]
there is strange problem with "string-replace" module when I tried to install "lib-jitsi-meet"

I use "windows 10" and "Mac os x EL Capitan version 10.11.3 "
