### ISSUE TITLE
local-video-recording?

### ISSUE THREAD

**Issue by OmarJay1** [jitsi/lib-jitsi-meet#2044]
Hello, is local-video-recording implemented in lib-jitsi-meet or are there any plans to do so?  Basically this feature:

[local-video-recording](https://github.com/jitsi/jitsi-meet/pull/11338)

If it's not there I was going to open a fork and try to hack something in, but I don't want to reproduce work.

Thanks.

**Comment by saghul** [comment]
lib-jitsi-meet is a lower level library.

As you can see from the Jitsi Meet PR there is no cooperation needed from LJM, so it's implemented in the application layer.

Since Jitsi Meet is also Apache 2 licensed you are welcome to take any or all the parts of our implementation, as long as you respect such license.
