### ISSUE TITLE
Screening Sharing Not Getting Above 5 FPS

### ISSUE THREAD

**Issue by ProdigyView** [jitsi/lib-jitsi-meet#2298]
I am re-opening the issue presented here:

https://github.com/jitsi/lib-jitsi-meet/issues/1089

But also the issue isn't just with Jitsi but a bug with Chrome as presented here:

https://bugs.chromium.org/p/webrtc/issues/detail?id=13016

The fix in the above was to set contentHint to motion. In Jitsi, I accomplished this will the following:

```
for (const track of tracks) {
                    
                    if (track.type === MediaType.VIDEO
                        && track.videoType === 'desktop') {
                        this.setVideoTrackContentHints(track.track, 'motion');
                    }
                }
```

The section of the code that was changed was this: https://github.com/jitsi/lib-jitsi-meet/blob/9db908a3658c05674f48e8dd356ceafe8bb5fa88/JitsiMeetJS.ts#LL336C16-L336C16

But it seems to be still be capped at 5 fps. Any thoughts?

**Comment by DanielMcAssey** [comment]
For desktop share the content hint should stay as detail, if set to motion it degrades the quality significantly that its hard to read text on desktop shares.

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
I agree with @ProdigyView that we should set the contentHint to 'motion' when the captured fps > 5. I am working on fixing this. For low fps screenshare, we set the contentHint to 'detail' and send only the highest spatial resolution and for high fps screenshare we need to set the contentHInt to 'motion' and send all the spatial-temporal layers so that the jvb can pick the best spatial-temporal layer based on the receivers BWE.
