### ISSUE TITLE
VideoBridge ignores `channelLastN` option

### ISSUE THREAD

**Issue by webintoit** [jitsi/lib-jitsi-meet#384]
Tested with current `lib-jitsi-meet` and videobridge from `jitsi-meet-unstable` (1810) version. 
When some user joined to conference, some of videos of other participants stay `black`. It may be happened when this videos not in lastN, i think. Problem solves itself when users, which video is not displaying, will mute then unmute their videos.
I set config option `channelLastN: -1`, but i still receive `last_n_changed` event. It looks like `adaptiveLastN` works, but it disabled in config.

**Comment by bgrozev** [comment]
Last-n is an upper limit of the streams to receive. That is, the bridge is free to send less video streams that last-n, but not more. Recently the adaptive stuff was enabled by default (the config option is obsolete, AFAIK), and this would explain why you are only seeing the problem now. But this is by design. 
The notification from the bridge will always be sent, and although it contains the name "last-n", it will always just list the streams which are currently forwarded.

**Comment by webintoit** [comment]
Thanks!
