### ISSUE TITLE
[Edge] Device selection does not work

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#530]
In Edge, the device selector UI shows grayed drop down lists for mic and webcam. Working on it.

The console says: "Failed to get access to local media. Error ". The call to `getUserMedia()` fails. Let's see why.

**Comment by ibc** [comment]
OK, the first problem was due the usage of `exact` in `getUserMedia()`.  It happens that Edge does not support 640x480. Using `ideal` instead of `exact` fixes the issue.

**Comment by ibc** [comment]
Now the issue is that the audio/video selection buttons are disabled. I see no reason given that I've checked that `enumerateDevices()` works nicely in Edge and produces good data.

**Comment by ibc** [comment]
I wonder if this issue (the list of devices not shown) has any relationship with #529. Just wondering: may be a React+Edge issue here?

**Comment by saghul** [comment]
I don't think so, since React is just rendering the data we give it. I'll take a closer look tomorrow.

**Comment by virtuacoplenny** [comment]
Do you see the same issue with IE11? What I see on meet.jit.si is that you can switch but on beta.meet.jit.si the dropdown changes to "permission not granted." I too don't think it's a react + edge issue if the dropdown itself is disabled. I'm thinking the react components are simply respecting whatever gets passed into them.

**Comment by virtuacoplenny** [comment]
For IE11, it's not possible to have multiple video tracks from the same camera. This works okay on meet.jit.si because it has older UI-data-flow behavior where "hasVideoPermission" was passed in one time as a boolean to device selection, so subsequent failure to obtain the video track for the device selection preview would kind of be ignored (I'm surprised there were no other consequences...). The latest jitsi-meet passes a function into "hasVideoPermission" so likely after the getUserMedia error, somewhere the lib sets the boolean that permission is not granted, and something triggers a re-render of device selection, causing the dropdown to be disabled.

Maybe some of the behavior described applies to the issue you're seeing.

**Comment by ibc** [comment]
To clarify: Getting two local MediaStream with webcam video does work in Edge. So, the `getUserMedia()` call (to show the video preview) does work in Edge when opening the devices selector.

The problem is just that the list of the media devices is not passed to the UI component (may be some `if (browser === xxxx)` check somewhere that I've missed).

**Comment by ibc** [comment]
@saghul remember to close this (and let me know where the exact issue was, please).

**Comment by saghul** [comment]
I amended the Edge patch before landing it. The specific diff is here: https://github.com/jitsi/lib-jitsi-meet/commit/e4133e067b64544e3796d2ad901b649ce9743186#diff-7d21489f2da42a0c08c868715b66dcddR1304 Thanks for the reminder!
