### ISSUE TITLE
Does lib-jitsi-meet support one-way streaming? 

### ISSUE THREAD

**Issue by Kukunin** [jitsi/lib-jitsi-meet#670]
Hello. I'm trying to use jitsi for one-way streaming. But I encounter a number of problems when other participants don't stream their tracks.

- SDP still sets to `sendrecv` even if there are not local tracks
- video freezes after the third participant is joined (there is no p2p, but I believe something wrong with `Last N` and dominant speaker

I have a common question before I start investigation too deeply: does jitsi support one-way streaming? Are there known issues might be when only one participant streams his tracks? Are all components might be affected: `lib-jitsi-meet`, `jicofo`, `jvb`? 

Any help is appreciated. Thanks

**Comment by bbaldino** [comment]
i think it should, though it's not a case we exercise so there may be a little work to be done.  you had another thread going with this somewhere, right?  the sendrecv is probably from this: https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/LocalSdpMunger.js#L107

the video freezing is probably because: rtcp feedback includes a 'send ssrc' for the packet itself, it usually uses the video send ssrc for this.  if you don't have a video send ssrc, it uses the ssrc `1`.  i thought the bridge now automatically accepted rctp with an ssrc of `1` (@gpolitis, can you confirm?), but i'm not sure what your setup is so that may be the cause of the freezes.

**Comment by sapkra** [comment]
Is this still a problem or can it be closed?

**Comment by Kukunin** [comment]
@sapkra I believe this can be closed since:
- it's old and outdated
- it can be worked around, so it's not a blocker
