### ISSUE TITLE
Avoiding jitsi-meet-tokens dependency on prosody-trunk

### ISSUE THREAD

**Issue by gmemon** [jitsi/lib-jitsi-meet#787]
Hello,

We are trying to use jitsi-meet-tokens for room authorization. But, jitsi-meet-tokens takes a dependency on prosody-trunk, which is nightly built. I understand why that is the case. For room authorization to work, jitsi-meet-tokens needs muc-room-pre-create and muc-occupant-pre-join events, and prosody's current stable branch does not provide these events. Still, taking a dependency on prosody-trunk is troublesome. So, would it be possible to fire these 2 events from prosody's stable branch? If so, can you please tell me how easy/hard it might be? If that would be too challenging, then is there a prosody-trunk version that you would recommend?

Thanks,
-Ghulam

**Comment by damencho** [comment]
I cannot give you details on the prosody stable code. But yeah the tokens have a dependency of prosody trunk, because of also a bosh session event.
For a long time we are using prosody trunk 747 when deploying meet.jit.si (open 2 tabs on meet.jit.si and in the js console you can filter by version and you will see the versions that are used). So I will recommend that one.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
